### ISSUE TITLE
No license for this project?

### ISSUE THREAD

**Issue by abdavis** [nelhage/ultimattt#9]
I saw that there was no license declared for this repository. I was thinking of porting to wasm and and using yew for a high performance in-browser tic tac toe ai. I would probably be going open source. Of course with no license, I believe legally the code is _not_ open source and isn't available to be used/modified. If you don't want to license it, that's cool too and I could start from scratch.

**Comment by nelhage** [comment]
Added an Apache license! Thanks for flagging.
